config/routes.rb
Sandworm::Application.routes.draw do

   resources :products
   resources :formats
   resources :media
   resources :series
   resources :product_types
   resources :categories
   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   resources :contacts, only: [:new, :create]

   root to: 'static_pages#home'
                                       
   match '/help',    to: "static_pages#help",     via: 'get'
   match '/about',   to: "static_pages#about",    via: :get
   match '/order',   to: "static_pages#order",    via: :get
   match '/contact', to: "contacts#new",  via: :get

   match '/signup',  to: 'users#new',             via: :get       
   match '/signin',  to: 'sessions#new',          via: :get 
   match '/signout', to: 'sessions#destroy',     via: :delete
   

  

end

app/models/format.rb
class Format < ActiveRecord::Base
#  attr_accessible :height, :length, :medium_id, :name, :weight, :width
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
   before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy, :index, :show]

  # GET /formats
  def index
    @formats = Format.all
  end

  # GET /formats/1
  def show
    @format = Format.find(params[:id])
  end

  # GET /formats/new
  def new
    @format = Format.new
  end

  # GET /formats/1/edit
  def edit
    @format = Format.find(params[:id])
  end

  # POST /formats
  def create
    @format = Format.new(permitted_params.format)

    if @format.save
      redirect_to @format, notice: 'Format was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /formats/1
  # PUT /formats/1.json
  def update
    @format = Format.find(params[:id])

    if @format.update_attributes(permitted_params.format)
      redirect_to @format, notice: 'Format was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /formats/1
  # DELETE /formats/1.json
  def destroy
    @format = Format.find(params[:id])
    @format.destroy

    redirect_to formats_url
  end
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/_form.html.erb
<%= form_for(@format) do |f| %>
  <% if @format.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@format.errors.count, "error") %> prohibited this format from being saved:</h2>

      <ul>
      <% @format.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :medium_id %><br />
    <%= f.number_field :medium_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formats/edit.html.erb
<h1>Editing format</h1>

<%= render 'form' %>

<%= link_to 'Show', @format %> |
<%= link_to 'Back', formats_path %>

app/views/formats/index.html.erb
<h1>Listing formats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Width</th>
    <th>Length</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Medium</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @formats.each do |format| %>
  <tr>
    <td><%= format.name %></td>
    <td><%= format.width %></td>
    <td><%= format.length %></td>
    <td><%= format.height %></td>
    <td><%= format.weight %></td>
    <td><%= format.medium_id %></td>
    <td><%= link_to 'Show', format %></td>
    <td><%= link_to 'Edit', edit_format_path(format) %></td>
    <td><%= link_to 'Destroy', format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Format', new_format_path %>

app/views/formats/new.html.erb
<h1>New format</h1>

<%= render 'form' %>

<%= link_to 'Back', formats_path %>

app/views/formats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @format.name %>
</p>

<p>
  <b>Width:</b>
  <%= @format.width %>
</p>

<p>
  <b>Length:</b>
  <%= @format.length %>
</p>

<p>
  <b>Height:</b>
  <%= @format.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @format.weight %>
</p>

<p>
  <b>Medium:</b>
  <%= @format.medium_id %>
</p>


<%= link_to 'Edit', edit_format_path(@format) %> |
<%= link_to 'Back', formats_path %>