config/routes.rb
Sandworm::Application.routes.draw do

   resources :products
   resources :formats
   resources :media
   resources :series
   resources :product_types
   resources :categories
   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   resources :contacts, only: [:new, :create]

   root to: 'static_pages#home'
                                       
   match '/help',    to: "static_pages#help",     via: 'get'
   match '/about',   to: "static_pages#about",    via: :get
   match '/order',   to: "static_pages#order",    via: :get
   match '/contact', to: "contacts#new",  via: :get

   match '/signup',  to: 'users#new',             via: :get       
   match '/signin',  to: 'sessions#new',          via: :get 
   match '/signout', to: 'sessions#destroy',     via: :delete
   

  

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
   before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]
  # GET /series
  # GET /series.json

  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @series = Series.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/new
  # GET /series/new.json
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(permitted_params.series)
    if @series.save
      redirect_to @series, notice: 'Series was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /series/1
  # PUT /series/1.json
  def update
    @series = Series.find(params[:id])

    if @series.update_attributes(permitted_params.series)
      redirect_to @series, notice: 'Series was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    redirect_to series_index_url
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :zinewiki %><br />
    <%= f.text_field :zinewiki %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Zinewiki</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @series.each do |series| %>
  <tr>
    <td><%= series.name %></td>
    <td><%= series.url %></td>
    <td><%= series.zinewiki %></td>
    <td><%= link_to 'Show', series %></td>
    <td><%= link_to 'Edit', edit_series_path(series) %></td>
    <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<% provide(:title, @series.name )%>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @series.name %>
</p>

<p>
  <b>Url:</b>
  <%= @series.url %>
</p>

<p>
  <b>Zinewiki:</b>
  <%= @series.zinewiki %>
</p>


<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>