config/routes.rb
Sandworm::Application.routes.draw do

   resources :products
   resources :formats
   resources :media
   resources :series
   resources :product_types
   resources :categories
   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   resources :contacts, only: [:new, :create]

   root to: 'static_pages#home'
                                       
   match '/help',    to: "static_pages#help",     via: 'get'
   match '/about',   to: "static_pages#about",    via: :get
   match '/order',   to: "static_pages#order",    via: :get
   match '/contact', to: "contacts#new",  via: :get

   match '/signup',  to: 'users#new',             via: :get       
   match '/signin',  to: 'sessions#new',          via: :get 
   match '/signout', to: 'sessions#destroy',     via: :delete
   

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
   <small>
		<!-- %= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %-->  
		<%= link_to image_tag("Edge_Rails_logo.png", alt: "Edge Rails"), 'http://edgeguides.rubyonrails.org/' %>  

		
   </small>
   <nav>
      <ul>
         <li><%= link_to "About", about_path %></li>
         <li><%= link_to "Contact", contact_path %></li>
         <li><%= link_to "Help",    help_path %></li>
      </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header> <class="navbar navbar-fixed-top">
   
	<div class="container center">
		<div>
			<h1><a href="/">Great Worm Express Distro</a></h1>
      </div>
		<nav>
         <ul class="nav-menu">
            <li><%= link_to "Home",    root_path %></li>
	         <li><%= link_to "Order", order_path %></li>
  	      <% if signed_in? %>
  	    		<li><%= link_to "Profile", current_user %></li>
  	  			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
  				<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
  			<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
	  		<% end %>
         </ul> 
			<% if !current_user.nil? && current_user.admin? %>
				<ul class="nav-menu">
					<li>Admin tasks:</li>
					<li><%= link_to "Products", products_path %></li>
					<li><%= link_to "Series", series_index_path %></li>
					<li><%= link_to "Media", media_path %></li>
					<li><%= link_to "Formats", formats_path %></li>
               <li><%= link_to "Categories", categories_path %></li>
					<li><%= link_to "Users", users_path %></li>

				</ul>
			<% end %>	
      </nav>
   </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.ico' %>
     <!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
     <![endif]-->
 	</head>
<body>
	<div id="wrapper">
	<%= render 'layouts/header'%>
   <div class="container">

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		
		<%= render 'layouts/footer'%>
      
   </div>
	<%= debug(params) if Rails.env.development? %>

	</div>
</body>
</html>